name: Continuous Integration
on:
  workflow_dispatch:
#  pull_request:
  push:
    branches:
#      - main
      - 'releases/*'
      - 'feature/*'

jobs:
   test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      ### Set up Fortify ScanCentral Client ###
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1
        with:
          version: 23.1.0  
          client-auth-token: "token"
          
      # Retrieve CLIs
      - name: Download CLIs
        run: |
          cd "/opt/hostedtoolcache/Fortify ScanCentral/23.1.0/x64/bin"
          wget -qO- https://github.com/fortify/fcli/releases/download/v1.3.1/fcli-linux.tgz | tar zxf -  


      - name: Test Local Action
        if: always()
        id: test-action
        uses: ./
        env:
          FCLI_DEFAULT_TOKEN_EXPIRE: "1h"
        with:
            ssc_base_url: ${{ vars.FTFY_SSC_URL}}
            ssc_ci_username: ${{ secrets.FTFY_CI_USERNAME }}
            ssc_ci_password: ${{ secrets.FTFY_CI_PASSWORD }}
            ssc_app: "github_action_dev_app"
            ssc_version: "1.0"

      - name: Test Local Action (CI Token)
        if: always()
        uses: ./
        with:
            ssc_base_url: ${{ vars.FTFY_SSC_URL}}
            ssc_ci_token: ${{ secrets.FTFY_CI_TOKEN_DEC }}
            ssc_app: "github_action_dev_app"
            ssc_version: "1.0"

      - name: Test Local  (UP)
        if: always()
        uses: ./
        with:
            ssc_base_url: ${{ vars.FTFY_SSC_URL}}
            ssc_ci_username: ${{ secrets.FTFY_CI_USERNAME }}
            ssc_ci_password: ${{ secrets.FTFY_CI_PASSWORD }}
            ssc_app: "github_action_dev_app"
            ssc_version: "1.0"
    
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
